"""init_charge_points_table

Revision ID: 0002
Revises: 0001
Create Date: 2023-07-11 13:37:57.061158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('charge_points',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('description', sa.String(length=48), nullable=True),
    sa.Column('status', sa.Enum('AVAILABLE', 'OFFLINE', 'RESERVED', 'CHARGING', name='chargepointstatus'), nullable=True),
    sa.Column('last_heartbeat', sa.DateTime(), nullable=True),
    sa.Column('location_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_charge_points_status'), 'charge_points', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_charge_points_status'), table_name='charge_points')
    op.drop_table('charge_points')
    # ### end Alembic commands ###
